# Generated by Django 3.2.18 on 2023-04-13 20:21

import core.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('footer_links', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('label', wagtail.blocks.TextBlock(label='Título', required=True)), ('url', wagtail.blocks.TextBlock(label='Url', required=False)), ('document', core.blocks.DocumentChooserBlock(label='Documento', required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Enlaces')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sup_title', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Título')),
                ('content', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('payment_methods', wagtail.fields.StreamField([('logo', wagtail.blocks.StructBlock([('logo', core.blocks.ImageChooserBlock(help_text='Tamaño recomendado 120x75.', label='Logo', required=False)), ('observation', wagtail.blocks.TextBlock(label='Observación', required=False))]))], blank=True, null=True, use_json_field=True, verbose_name='Puntos de Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(blank=True, help_text='Tamaño recomendado: 2880 x 1400', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('full_attention', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Atención 24hs')),
                ('full_assistance', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Asistencia 24hs')),
                ('app_store_url', models.URLField(blank=True, null=True, verbose_name='Link de App Store')),
                ('google_play_url', models.URLField(blank=True, null=True, verbose_name='Link de Google Play')),
                ('messages_and_calls', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Línea baja y WhatsApp')),
                ('home_address', models.TextField(blank=True, null=True, verbose_name='Dirección casa matriz')),
                ('emails', models.TextField(blank=True, null=True, verbose_name='Correos')),
                ('opening_hours', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Horarios de atención')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Link a Facebook')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Link a Instagram')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Link a LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informaciones',
                'verbose_name_plural': 'Informaciones',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReinsurersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reinsurers_items', to='core.homepage')),
            ],
            options={
                'verbose_name': 'Reseguradora',
                'verbose_name_plural': 'Reaseguradores',
            },
        ),
        migrations.CreateModel(
            name='FooterDocumentItemSecondColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(verbose_name='Título')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_document_second_column', to='core.footerpage')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FooterDocumentItemFirstColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.TextField(verbose_name='Título')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_document_first_column', to='core.footerpage')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['sort_order'],
            },
        ),
    ]
